In [3]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [4]:
#create a dataframe to read dataset
df=pd.read_csv(r"..\API\data\processed\train_data.csv")

In [6]:
df.head()

,service,flag,src_bytes,dst_bytes,same_srv_rate,diff_srv_rate,dst_host_srv_count,dst_host_same_srv_rate,dst_host_diff_srv_rate,dst_host_serror_rate,class
0,-0.645371,0.753006,-0.009889,-0.039309,0.772093,-0.349275,-0.813968,-0.779141,-0.280668,-0.641791,1
1,0.768910,0.753006,-0.010032,-0.039309,-1.320540,0.490826,-1.030875,-1.157808,2.764349,-0.641791,1
2,1.090338,-0.739909,-0.010092,-0.039309,-1.388778,0.042772,-0.804931,-0.935063,-0.173825,1.603803,0
3,-0.452515,0.753006,-0.009996,0.052472,0.772093,-0.349275,1.264717,1.069642,-0.440932,-0.574424,1
4,-0.452515,0.753006,-0.010010,-0.034581,0.772093,-0.349275,1.264717,1.069642,-0.440932,-0.641791,1

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25192 entries, 0 to 25191
Data columns (total 11 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   service                 25192 non-null  float64
 1   flag                    25192 non-null  float64
 2   src_bytes               25192 non-null  float64
 3   dst_bytes               25192 non-null  float64
 4   same_srv_rate           25192 non-null  float64
 5   diff_srv_rate           25192 non-null  float64
 6   dst_host_srv_count      25192 non-null  float64
 7   dst_host_same_srv_rate  25192 non-null  float64
 8   dst_host_diff_srv_rate  25192 non-null  float64
 9   dst_host_serror_rate    25192 non-null  float64
 10  class                   25192 non-null  int64
dtypes: float64(10), int64(1)
memory usage: 2.1 MB

In [8]:
df.shape

(25192, 11)

In [9]:
df.describe()

,service,flag,src_bytes,dst_bytes,same_srv_rate,diff_srv_rate,dst_host_srv_count,dst_host_same_srv_rate,dst_host_diff_srv_rate,dst_host_serror_rate,class
count,2.519200e+04,2.519200e+04,2.519200e+04,2.519200e+04,2.519200e+04,2.519200e+04,2.519200e+04,2.519200e+04,2.519200e+04,2.519200e+04,25192.000000
mean,2.919227e-17,-1.642947e-16,5.880762e-17,4.449354e-17,-5.091020e-17,-2.760574e-17,-8.038452e-17,-4.117944e-17,8.108965e-18,-4.971148e-17,0.533860
std,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,0.498862
min,-1.866796e+00,-2.606053e+00,-1.009232e-02,-3.930901e-02,-1.502509e+00,-3.492750e-01,-1.039912e+00,-1.157808e+00,-4.409317e-01,-6.417913e-01,0.000000
25%,-6.453714e-01,-7.399092e-01,-1.009232e-02,-3.930901e-02,-1.297794e+00,-3.492750e-01,-9.495348e-01,-1.046435e+00,-4.409317e-01,-6.417913e-01,0.000000
50%,-4.525148e-01,7.530060e-01,-1.007407e-02,-3.930901e-02,7.720933e-01,-3.492750e-01,-4.886089e-01,-2.180853e-02,-2.806677e-01,-6.417913e-01,1.000000
75%,1.090338e+00,7.530060e-01,-9.976595e-03,-3.333979e-02,7.720933e-01,-1.323468e-02,1.264717e+00,1.069642e+00,-6.698237e-02,1.603803e+00,1.000000
max,2.311763e+00,1.126235e+00,1.583225e+02,5.795172e+01,7.720933e-01,5.251397e+00,1.264717e+00,1.069642e+00,4.901202e+00,1.603803e+00,1.000000